version: '3'

services:
  your-app:
    image: openjdk:17
    container_name: techihub
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./target/job-0.0.1-SNAPSHOT.jar:/app/job-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "job-0.0.1-SNAPSHOT.jar"]
