server:
  address: 0.0.0.0
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://techihub-techily.postgres.database.azure.com:5432/postgres?user=techihub&password=area57@5298!!&sslmode=require
    username: techihub
    password: area57@5298!!
    driver-class-name: org.postgresql.Driver
    ssl: true
    ssl-root-cert: classpath:azure-database-certificate.crt

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: samwelnjunji@gmail.com
    password: bsmjtwmhyvspszzp
    properties:
      enable: true
      auth: true
      mail:
        smtp:
          starttls:
            enable: true

# MVC Configuration
mvc:
  contentnegotiation:
    favor-parameter: false
    favor-path-extension: true
    defaultContentType: application/JSON
    mediaType:
      json: application/JSON

# Email regex pattern
custom:
  validation:
    email:
      pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
      # Password regex pattern
    password:
      pattern: '^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$'

# JWT Configuration
jwt:
  token:
    prefix: Bearer
    expiration-time: 86400000
  refresh-token:
    expiration: 604800000


runtime: java
env: standard
instance_class: F2

handlers:
  - url: /.*
    script: this field is required, but ignored

automatic_scaling:
  target_cpu_utilization: 0.65
