name: Deploy to Azure

on:
  push:
    branches:
      - workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: pelikan-techihub
          publish-profile: |
            <publishData><publishProfile profileName="pelikan-techihub - Web Deploy" publishMethod="MSDeploy" publishUrl="pelikan-techihub.scm.azurewebsites.net:443" msdeploySite="pelikan-techihub" userName="$pelikan-techihub" userPWD="AQKLAXI8DZGBSo1OaGmnNEo0A6s3sgE.5J1M9LHYxGUvgQst6jkYiwNwFiGyGKzA94__ltE4Qac" destinationAppUrl="https://pelikan-techihub.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="pelikan-techihub - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-351.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="pelikan-techihub\$pelikan-techihub" userPWD="AQKLAXI8DZGBSo1OaGmnNEo0A6s3sgE.5J1M9LHYxGUvgQst6jkYiwNwFiGyGKzA94__ltE4Qac" destinationAppUrl="https://pelikan-techihub.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="pelikan-techihub - Zip Deploy" publishMethod="ZipDeploy" publishUrl="pelikan-techihub.scm.azurewebsites.net:443" userName="$pelikan-techihub" userPWD="AQKLAXI8DZGBSo1OaGmnNEo0A6s3sgE.5J1M9LHYxGUvgQst6jkYiwNwFiGyGKzA94__ltE4Qac" destinationAppUrl="https://pelikan-techihub.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          package: target/*.jar
